language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - composer self-update

install: composer update

script: phpunit -v --coverage-text
